// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/Users/rezajafar/.Trash/peakofeloquence-app 12.55.43 AM/app.config";
import type { default as appConfig1 } from "/Users/rezajafar/.Trash/peakofeloquence-app 12.55.43 AM/node_modules/@nuxt/ui-pro/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}