// Generated by nuxt-site-config

declare module 'nitropack' {
  interface NitroRouteRules {
    site?: import('../../node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
  interface NitroRouteConfig {
    site?: import('../../node_modules/nuxt-site-config/dist/runtime/types').SiteConfig
  }
}

declare module 'h3' {
  interface H3EventContext {
    siteConfig: import('../../node_modules/nuxt-site-config/dist/runtime/types').SiteConfigStack
  }
}

declare module 'nuxt/schema' {
  interface AppConfigInput {
    /** Theme configuration */
    site?: import('../../node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
}

declare module '@nuxt/schema' {
  interface AppConfigInput {
    /** Theme configuration */
    site?: import('../../node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
  interface Nuxt {
    _siteConfig?: import('../../node_modules/nuxt-site-config/dist/runtime/types').SiteConfigStack
  }
}

declare module '@nuxt/schema' {
  export interface RuntimeNuxtHooks {
    'site-config:resolve': (siteConfig: import('../../node_modules/nuxt-site-config/dist/runtime/types').SiteConfig) => void
  }
}

export {}
