// Generated by nuxt-og-image

declare module 'nitropack' {
  interface NitroRouteRules {
    ogImage?: false | import('../../node_modules/nuxt-og-image/dist/runtime/types').OgImageOptions
  }
  interface NitroRouteConfig {
    ogImage?: false | import('../../node_modules/nuxt-og-image/dist/runtime/types').OgImageOptions
  }
}
export {}
